baseURL = 'https://example.org/'
title = 'Zan'
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = false
enableRobotsTXT = true

[languages]
  [languages.zh]
    languageCode = 'zh-CN'
    languageName = '简体中文'
    contentDir = 'content/zh'
    weight = 1
  [languages.en]
    languageCode = 'en-US'
    languageName = 'English'
    contentDir = 'content/en'
    weight = 2