[[main]]
name = "HOME"
url = "/"
weight = 10

[[main]]
name = "SWITCHGEAR"
url = "/switchgear/"
weight = 11

[[main]]
name = "COMPACT SUBSTATION"
url = "/substation/"
weight = 12

[[main]]
name = "OIL-IMMERSED TRANSFORMER"
url = "/oil-immersed/"
weight = 13

[[main]]
name = "DRY-TYPE TRANSFORMER"
url = "/dry-type/"
weight = 14

[[main]]
name = "INSIGHTS"
url = "insights/"
weight = 30

[[main]]
name = "CONTACT"
url = "contact/"
weight = 40


# footer menu
[[footer]]
name = "隐私"
url = "about/"
weight = 1

[[footer]]
name = "常见问题"
url = "about/"
weight = 2