[[main]]
name = "首页"
url = "/"
weight = 10

[[main]]
name = "开关柜"
url = "/switchgear/"
weight = 11

[[main]]
name = "箱式变电站"
url = "/substation/"
weight = 12

[[main]]
name = "油浸式变压器"
url = "/oil-immersed/"
weight = 13

[[main]]
name = "干式变压器"
url = "/dry-type/"
weight = 14

[[main]]
name = "行业洞察"
url = "insights/"
weight = 30

[[main]]
name = "联系我们"
url = "contact/"
weight = 40


# footer menu
[[footer]]
name = "隐私"
url = "about/"
weight = 2

[[footer]]
name = "常见问题"
url = "about/"
weight = 4