[[main]]
name = "首页"
pageRef = "/"
weight = 10

[[main]]
name = "产品"
pageRef = "/product"
identifier = "product"
weight = 20

  [[main]]
  name = "高低压开关柜"
  pageRef = "/product/switchgear"
  parent = "product"
  weight = 21

  [[main]]
  name = "箱式变电站"
  pageRef = "/product/substation"
  parent = "product"
  weight = 22

  [[main]]
  name = "油浸式变压器"
  pageRef = "/product/oil-immersed"
  parent = "product"
  weight = 23

  [[main]]
  name = "干式变压器"
  pageRef = "/product/dry-type"
  parent = "product"
  weight = 24


[[main]]
name = "资源中心"
pageRef = "/resources"
identifier = "resources"
weight = 30

  [[main]]
  name = "行业洞察"
  pageRef = "/resources/insights"
  parent = "resources"
  weight = 31

  [[main]]
  name = "客户案例"
  pageRef = "/resources/case-studies"
  parent = "resources"
  weight = 32

  [[main]]
  name = "常见问题"
  pageRef = "/resources/faq"
  parent = "resources"
  weight = 33

[[main]]
name = "关于公司"
pageRef = "/about"
weight = 38

[[main]]
name = "联系我们"
pageRef = "/contact"
weight = 40


# footer menu
[[footer]]
name = "隐私政策"
pageRef = "/footer/privacy-policy"
weight = 1

[[footer]]
name = "网站条款"
pageRef = "/footer/terms-conditions"
weight = 2

[[footer]]
name = "Cookie 政策"
pageRef = "/footer/cookie-policy"
weight = 3

[[footer]]
name = "免责声明"
pageRef = "/footer/disclaimer"
weight = 4