[[main]]
name = "HOME"
pageRef = "/"
weight = 10

[[main]]
name = "SWITCHGEAR"
pageRef = "/product/switchgear"
weight = 11

[[main]]
name = "COMPACT SUBSTATION"
pageRef = "/product/substation"
weight = 12

[[main]]
name = "OIL-IMMERSED TRANSFORMER"
pageRef = "/product/oil-immersed"
weight = 13

[[main]]
name = "DRY-TYPE TRANSFORMER"
pageRef = "/product/dry-type"
weight = 14

[[main]]
name = "RESOURCES"
pageRef = "/resources"
identifier = "resources"
weight = 30

  [[main]]
  name = "Isights"
  pageRef = "/resources/insights"
  parent = "resources"
  weight = 31

  [[main]]
  name = "Case Studies"
  pageRef = "/resources/case-studies"
  parent = "resources"
  weight = 32

[[main]]
name = "CONTACT"
pageRef = "/contact"
weight = 40


# footer menu
[[footer]]
name = "Privacy Policy"
pageRef = "/footer/privacy-policy"
weight = 1

[[footer]]
name = "FAQ"
pageRef = "/footer/faq"
weight = 2