company_name = "HengLi Transformer"
logo = "images/logo.png"

email = "weibenlong6@gmail.com"
phone = "+86 13792998878"
business_hours = "Mon–Sat, 8:00 AM–5:00 PM (GMT+8)"
address = "No. 408, Keji Xincheng, Customs Road, Linyi Economic and Technological Development Zone, Shandong Province"

turnstile_sitekey = "0x44AAAAAA"
