company_name = "Baoheng Plastic"
logo = "images/logo.png"

email = "weibenlong6@gmail.com"
phone = "+86 13325077372"
address = "Xianghe Industrial Park, Linyi City, Shandong, China"

turnstile_sitekey = "0x44AAAAAA"
